### ISSUE TITLE
`pik config` fails: undefined method + for nil:NilClass

### ISSUE THREAD

**Issue by klauern** [vertiginous/pik#104]
I don't have anything special that I know of in my OS (WinXP):

```
PS C:\mydocs> pik config
** CURRENT CONFIGURATION **


There was an error.
 Error: undefined method `+' for nil:NilClass

  in: pik/commands/config_command.rb:42:in `list'
  in: pik/commands/config_command.rb:11:in `execute'
  in: pik_runner:33
```

**Comment by fakeleft** [comment]
+1
