### ISSUE TITLE
Devkit install fails with a 404

### ISSUE THREAD

**Issue by jaredholdcroft** [vertiginous/pik#111]
Hi,

I'm using pik 0.3.0 pre and I've having trouble installing the devkit package. It looks like that version is no longer available. 

```
C:\Users\Jared\Projects>pik -v
pik 0.3.0.pre on Microsoft Windows [Version 6.1.7601]
by Gordon Thiesfeld (gthiesfeld@gmail.com)

C:\Users\Jared\Projects>pik package devkit install
INFO: Downloading:  http://cdn.rubyinstaller.org/archives/devkits/DevKit-tdm-32-  4.5.1-20101231-1457.7z
to:  C:\Users\Jared\.pik\downloads\DevKit-tdm-32-4.5.1-20101231-1457.7z
There was an error.
Error: Looking for http://cdn.rubyinstaller.org/archives/devkits/DevKit-tdm-32-4.5.1-20101231-1457.7z and all I got was a 404!
in: pik/contrib/uri_ext.rb:275:in `read'
in: net/http.rb:1054:in `request'
[snip]
```

I tried via the browser and it does indeed look like that file is unavailable. Is there a way of specifying and alternate url in the package install command?

Thanks,

Jared

**Comment by technogeeky** [comment]
I have this same problem. It would be solved by a more recent compiled version (on the downloads page).

The current source (the one on this page) has the newer, correct .exe devkit download. I'll try and install that manually, regenerate the pik-runner.exe, and see I can bootstrap a new version.

**Comment by technogeeky** [comment]
_sigh_ The devkit is just another MinGW/msys environment.
