### ISSUE TITLE
fails from msi

### ISSUE THREAD

**Issue by rdp** [vertiginous/pik#112]
after a clean install...

C:\installs\Console2>pik list
creating C:\Users\Administrator.pik

There was an error.
 Error: Permission denied - C:\Users\Administrator/.pik

  in: fileutils.rb:243:in `mkdir'
  in: fileutils.rb:243:in`fu_mkdir'
  in: fileutils.rb:217:in `mkpath'
  in: fileutils.rb:215:in`reverse_each'
  in: fileutils.rb:215:in `mkpath'
  in: fileutils.rb:201:in`each'
  in: fileutils.rb:201:in `mkpath'
  in: pathname.rb:1035:in`mkpath'
  in: pik/commands/command.rb:122:in `create'
  in: pik/commands/command.rb:62:in`initialize'
  in: pik_runner:26:in `new'
  in: pik_runner:26

pik_runner:34: undefined method `close' for Pik::List:Class (NoMethodError)

**Comment by rdp** [comment]
seems the error was caused by this faulty environment variable:

C:\dev\ruby\redcar>echo %HOME%
C:\Users\Administrator

C:\dev\ruby\redcar>echo %HOMEPATH%
\Users\packrd

Not sure how it got set up that way.
Sorry for the noise.
