### ISSUE TITLE
pik and gems

### ISSUE THREAD

**Issue by PandaWood** [vertiginous/pik#122]
I'm not sure what's going on here but it seems to me that pik doesn't set or use the gem_path properly or something?
I'm using GitBash.
Basically, no matter what or how many gems I install, after switching to a certain RVM (1.9.1) with pik, they are basically not installed.

pik use 191
 pik list
*191: ruby 1.9.1p378 (2010-01-10 revision 26273) [i386-mingw32]
 192: ruby 1.9.2p290 (2011-07-09) [i386-mingw32]
gem install bundler -v =1.0.3
successfully installed bundler-1.0.3

gem list
**\* LOCAL GEMS ***

It's not installed.
No matter how many gems I install, gem list, shows nothing.
To install pik, I did the "gem install" and followed the instructions, as of yesterday (ie latest version)

**Comment by jfabre** [comment]
I've got the exact same problem with git bash. It is stuck at version 192 for me and everything works fine until I execute pik use or pik sw. Then I lose all my gems.

If I use normal command line seems like everything works fine.

Even if I change the ruby version in command line it does not get applied in git bash.

Here is what I receive if I try to use rake under bundler

bundle exec rake -T
c:/Ruby/lib/ruby/1.9.1/rubygems.rb:762:in `report_activate_error': Could not find Rub
yGem bundler (>= 0) (Gem::LoadError)
        from c:/Ruby/lib/ruby/1.9.1/rubygems.rb:219:in`activate'
        from c:/Ruby/lib/ruby/1.9.1/rubygems.rb:1065:in `gem'
        from c:/Ruby187/bin/bundle:18:in`<main>'

Hope this helps.

**Comment by jasonkarns** [comment]
I've got the same problem.
Scenario: jruby 1.6.5 is my default

And here's my `gem environment` when executed from /c/ruby192/bin (executed against ruby 192 without using pik).
RubyGems Environment:
- RUBYGEMS VERSION: 1.7.2
- RUBY VERSION: 1.9.2 (2011-07-09 patchlevel 290) [i386-mingw32]
- INSTALLATION DIRECTORY: c:/Ruby192/lib/ruby/gems/1.9.1
- RUBY EXECUTABLE: c:/Ruby192/bin/ruby.exe
- EXECUTABLE DIRECTORY: c:/Ruby192/bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86-mingw32
- GEM PATHS:
  - c:/Ruby192/lib/ruby/gems/1.9.1
  - c:/Users/Jason/.gem/ruby/1.9.1
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/

Here's my `gem environment` when executed after `pik switch ruby 1.9.2`
RubyGems Environment:
- RUBYGEMS VERSION: 1.7.2
- RUBY VERSION: 1.9.2 (2011-07-09 patchlevel 290) [i386-mingw32]
- INSTALLATION DIRECTORY:
- RUBY EXECUTABLE: c:/Ruby192/bin/ruby.exe
- EXECUTABLE DIRECTORY: /bin
- RUBYGEMS PLATFORMS:
  - ruby
  - x86-mingw32
- GEM PATHS:
   -
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :benchmark => false
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - http://rubygems.org/

Notice that after using pik, the INSTALLATION DIRECTORY is blank. The EXECUTABLE DIRECTORY is different (/bin instead of /c/jruby192/bin). And GEM PATHS is blank.

**Comment by jasonkarns** [comment]
It looks like this may be a duplicate of Issue #63.

**Comment by jwebcat** [comment]
This happened for me as well I applied the fix from the issue # 63 to my .pikrc file and voila' :dancers: 

https://github.com/vertiginous/pik/issues/63
