### ISSUE TITLE
'pik install 1.9.2' failed - permission denied for fileutils.rb::rename

### ISSUE THREAD

**Issue by gbirchmeier** [vertiginous/pik#123]
I did a fresh install of pik on my WinXP platform.  I am an Admin user with all necessary read/write rights as far as I know.  I tried 'pik install 1.9.2' and got the following:

``` text
C:\Documents and Settings\Grant Birchmeier>pik install 1.9.2
INFO: Installing ruby-1.9.2-p136

INFO: Downloading:  http://rubyforge.org/frs/download.php/73723/ruby-1.9.2-p136-i386-mingw32.7z
      to:  C:\Documents and Settings\Grant Birchmeier\.pik\downloads\ruby-1.9.2-p136-i386-mingw32.7z

ruby-1.9.2-p136-i386-min...7z: 100% |oooooooooo|   5.8MB/  5.8MB Time: 00:00:09
INFO: Extracting:  C:\Documents and Settings\Grant Birchmeier\.pik\downloads\ruby-1.9.2-p136-i386-mingw32.7z
      to:  C:\Documents and Settings\Grant Birchmeier\.pik\rubies\ruby-1.9.2-p136


There was an error.
 Error: Permission denied - C:\Documents and Settings\Grant Birchmeier/.pik/rubies/ruby-1.9.2-p136/ruby-1.9.2-p136-i386-mingw32/bin or C:\Documents and Settings\Grant Bir
chmeier/.pik/rubies/ruby-1.9.2-p136/bin

  in: fileutils.rb:506:in `rename'
  in: fileutils.rb:506:in `mv'
  in: fileutils.rb:1397:in `fu_each_src_dest'
  in: fileutils.rb:1411:in `fu_each_src_dest0'
  in: fileutils.rb:1395:in `fu_each_src_dest'
  in: fileutils.rb:495:in `mv'
  in: pik/installer.rb:48:in `mv_r'
  in: pik/installer.rb:82:in `extract'
  in: pik/installer.rb:81:in `each'
  in: pik/installer.rb:81:in `extract'
  in: pik/installer.rb:74:in `each'
  in: pik/installer.rb:74:in `extract'
  in: pik/commands/install_command.rb:29:in `execute'
  in: pik_runner:27
```

Let me know if I can provide any other info that would help.

**Comment by samitheberber** [comment]
I had same kind of problem and when I saw this, I first updated pik and then installed ruby-1.9.2 and it was successfully installed. I did follow

```
$ pik up
$ pik install ruby 1.9.2
```

I use pik inside git-bash, so that's why $-chars.
