### ISSUE TITLE
DevKit download is forbidden.

### ISSUE THREAD

**Issue by ghost** [vertiginous/pik#149]
`pik package devkit install` fails with the following output:

```
INFO: Downloading:  http://cdn.rubyinstaller.org/archives/devkits/DevKit-tdm-32-4.5.1-20101231-1457.7z
      to:  C:\Users\<username>\.pik\downloads\DevKit-tdm-32-4.5.1-20101231-1457.7z


There was an error.
 Error: Failed to download http://cdn.rubyinstaller.org/archives/devkits/DevKit-tdm-32-4.5.1-20101231-1457.7z: Forbidden

  in: pik/contrib/uri_ext.rb:277:in `read'
  in: net/http.rb:1054:in `request'
  in: net/http.rb:2144:in `reading_body'
  in: net/http.rb:1053:in `request'
  in: net/http.rb:1037:in `request'
  in: net/http.rb:543:in `start'
  in: net/http.rb:1035:in `request'
  in: pik/contrib/uri_ext.rb:245:in `read'
  in: pik/contrib/uri_ext.rb:293:in `connect'
  in: pik/contrib/uri_ext.rb:240:in `read'
  in: pik/contrib/uri_ext.rb:120:in `download'
  in: tempfile.rb:188:in `open'
  in: pik/contrib/uri_ext.rb:118:in `download'
  in: pik/contrib/uri_ext.rb:60:in `download'
  in: pik/installer.rb:19:in `download'
  in: pik/commands/package_command.rb:40:in `devkit'
  in: pik/commands/package_command.rb:12:in `execute'
  in: pik_runner:27

```

**Comment by luislavena** [comment]
Hello, 

Can you try downloading and installing devkit using rubyinstaller.org download links and instructions instead?
