### ISSUE TITLE
on a failed directory could report better

### ISSUE THREAD

**Issue by rdp** [vertiginous/pik#20]
<pre>
There was an error
 Error: No such file or directory - "" -v

  in: pik/commands/run_command.rb:70:in ``'
  in: pik/commands/run_command.rb:70:in`echo_ruby_version'
  in: pik/commands/run_command.rb:11:in `execute'
  in: pik/commands/run_command.rb:8:in`each'
  in: pik/commands/run_command.rb:8:in `execute'
  in: pik:35

meant (but didn't actually say) "it appears that one of your ruby's has disappeared" and say which.
Thanks!
-r

**Comment by vertiginous** [comment]
Fixed in 78348d27d578fc08eaddcd70142773cd547e68ce

```
>pik run "echo."
IronRuby 0.9.0.0 on .NET 2.0.0.0


IronRuby 0.9.1.0 on .NET 2.0.0.0


jruby 1.3.1 (ruby 1.8.6p287) (2009-06-15 2fd6c3d) (Java HotSpot(TM) Client VM 1.6.0_14) [x86-java]


jruby 1.4.0RC1 (ruby 1.8.7 patchlevel 174) (2009-09-30 80c263b) (Java HotSpot(TM) Client VM 1.6.0_14) [x86-java]


jruby 1.4.0RC2 (ruby 1.8.7 patchlevel 174) (2009-10-21 7e77f32) (Java HotSpot(TM) Client VM 1.6.0_14) [x86-java]


ruby 1.8.5 (2006-12-25 patchlevel 12) [i386-mswin32]


ruby 1.8.6 (2008-08-11 patchlevel 287) [i386-mswin32]


ruby 1.8.6 (2009-03-31 patchlevel 368) [i386-mingw32]


ruby 1.9.1p129 (2009-05-12 revision 23412) [i386-mingw32]

There was an error.
 Error: Unable to find a Ruby executable at C:\ruby\191-p129-mingw32_2\bin

  in: pik/commands/run_command.rb:83:in `echo_ruby_version'
  in: pik/commands/run_command.rb:12:in `execute'
  in: pik/commands/run_command.rb:8:in `each'
  in: pik/commands/run_command.rb:8:in `execute'
  in: pik_runner:35

ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-mingw32]
```
