### ISSUE TITLE
pik checkup broken

### ISSUE THREAD

**Issue by vertiginous** [vertiginous/pik#36]
```
c:\Users\bosko\Documents\Projects>pik checkup

There was an error.
 Error: undefined method `empty?' for nil:NilClass

  in: pik/commands/checkup_command.rb:28:in `home'
  in: pik/commands/checkup_command.rb:9:in `execute'
  in: pik_runner:35
```

**Comment by vertiginous** [comment]
Fixed int 729dae5ec14ba90ab23f3cd99abb57f4d3df8161
