### ISSUE TITLE
gemsync fails with "Error: private method `split' called for nil:NilClass"

### ISSUE THREAD

**Issue by charlesroper** [vertiginous/pik#43]
http://pastie.org/730569

[ C:\ ]

> pik gemsync
> Select which Ruby you want:
> 1. 092: IronRuby 0.9.2.0 on .NET 2.0.0.0
> 2. 191: ruby 1.9.1p243 (2009-07-16 revision 24175) [i386-mingw32]
> 3. 186: ruby 1.8.6 (2009-08-04 patchlevel 383) [i386-mingw32]
> ?  2

There was an error.
 Error: private method `split' called for nil:NilClass

 in: pik/version_parser.rb:11:in `initialize'
 in: pik/version_parser.rb:6:in`new'
 in: pik/version_parser.rb:6:in `parse'
 in: pik/commands/gemsync_command.rb:25:in`platform_consistent?'
 in: pik/commands/gemsync_command.rb:15:in `execute'
 in: pik_runner:35

**Comment by rdp** [comment]
which versions of rubygems?
